[toolchain]
# The nightly toolchain is needed so the generated wasm generates
# a shared memory (via +atomics) instead of a non-shared one (default behavior)
# Using nightly-2024-08-02 for wasm-bindgen threading compatibility
channel = "nightly-2024-12-01"
targets = ["wasm32-unknown-unknown", "wasm32-wasi"]
components = ["rust-src", "rustfmt", "clippy"]
